#!/bin/bash
# Collect PRs, build instances, and refine problem statements for all target repos.
#
# Usage:
#   cd swe-factory-dev && bash run/collect_issues_prs.sh

set -euo pipefail

set -a
source "$(dirname "$0")/../.env"
set +a

SCRIPT_DIR="data_collection/collect"
DATA_DIR="/data/yuansui/internal-swe-bench-data"
CUTOFF_DATE="2026-12-31T23:59:59Z"


mkdir -p "$DATA_DIR/MiroMindAI__MiroThinker"
mkdir -p "$DATA_DIR/MiroMindAI__sd-torchtune"
mkdir -p "$DATA_DIR/MiroMindAI__miroflow"


# echo "=== [MiroThinker] Step 1: Collecting PRs ==="
# python3 "$SCRIPT_DIR/print_pulls.py" MiroMindAI/MiroThinker "$DATA_DIR/MiroMindAI__MiroThinker/prs.jsonl" --mode omnigirl

# echo "=== [sd-torchtune] Step 1: Collecting PRs ==="
# python3 "$SCRIPT_DIR/print_pulls.py" MiroMindAI/sd-torchtune "$DATA_DIR/MiroMindAI__sd-torchtune/prs.jsonl" --mode omnigirl

# echo "=== [miroflow] Step 1: Collecting PRs ==="
# python3 "$SCRIPT_DIR/print_pulls.py" MiroMindAI/miroflow "$DATA_DIR/MiroMindAI__miroflow/prs.jsonl" --mode omnigirl


# echo "=== [MiroThinker] Step 2: Building instances ==="
# python3 "$SCRIPT_DIR/build_dataset.py" \
#   "$DATA_DIR/MiroMindAI__MiroThinker/prs.jsonl" \
#   "$DATA_DIR/MiroMindAI__MiroThinker" \
#   --mode omnigirl --language python --cutoff_date "$CUTOFF_DATE"

# echo "=== [miroflow] Step 2: Building instances ==="
# python3 "$SCRIPT_DIR/build_dataset.py" \
#   "$DATA_DIR/MiroMindAI__miroflow/prs.jsonl" \
#   "$DATA_DIR/MiroMindAI__miroflow" \
#   --mode omnigirl --language python --cutoff_date "$CUTOFF_DATE"

# echo "=== [sd-torchtune] Step 2: Building instances ==="
# python3 "$SCRIPT_DIR/build_dataset.py" \
#   "$DATA_DIR/MiroMindAI__sd-torchtune/prs.jsonl" \
#   "$DATA_DIR/MiroMindAI__sd-torchtune" \
#   --mode omnigirl --language python --cutoff_date "$CUTOFF_DATE"


# # ── Step 3: Add version info to instances (in-place) ─────────────────────────
# export PYTHONPATH="$(cd "$(dirname "$0")/.."; pwd):${PYTHONPATH:-}"
# SETUP_DIR="testbed"

# # Helper: find the primary instances file (exclude _failures, _versions derivatives).
# find_instances_file() {
#   ls "$DATA_DIR/$1"/instances_all_*.jsonl 2>/dev/null \
#     | grep -v -E '_(failures|versions)' \
#     | head -1
# }

# for REPO in MiroMindAI__MiroThinker MiroMindAI__miroflow MiroMindAI__sd-torchtune; do
#   INSTANCE_FILE=$(find_instances_file "$REPO")
#   if [ -z "$INSTANCE_FILE" ]; then
#     echo "=== No instances_all file found for $REPO, skipping version step ==="
#     continue
#   fi

#   # Skip if ALL records already have version.
#   MISSING=$(python3 - "$INSTANCE_FILE" <<'PY'
# import json, sys
# path = sys.argv[1]
# missing = 0
# try:
#     with open(path, "r", encoding="utf-8") as f:
#         for line in f:
#             line = line.strip()
#             if not line:
#                 continue
#             obj = json.loads(line)
#             if "version" not in obj:
#                 missing += 1
# except FileNotFoundError:
#     pass
# print(missing)
# PY
#   )
#   if [ "$MISSING" = "0" ]; then
#     echo "=== All records in $INSTANCE_FILE already have version, skipping ==="
#     continue
#   fi
#   echo "=== $MISSING records missing version in $INSTANCE_FILE ==="

#   echo "=== Getting versions for $REPO ==="
#   python3 "$SCRIPT_DIR/get_version.py" \
#     --instance_path "$INSTANCE_FILE" \
#     --testbed "$SETUP_DIR" \
#     --max-workers 10 \
#     --in-place || echo "=== Warning: some instances failed version lookup for $REPO (continuing) ==="

#   # Clean up derivative files generated by get_version.py
#   rm -f "$DATA_DIR/$REPO"/*_failures*.jsonl "$DATA_DIR/$REPO"/*_versions*.jsonl
# done

# ── Step 4: Refine problem statements (commented out for now) ────────────────
echo "=== [MiroThinker] Step 4: Refining problem statements ==="
python3 "$SCRIPT_DIR/refine_problem_statements.py" "$DATA_DIR/MiroMindAI__MiroThinker"

echo "=== [miroflow] Step 4: Refining problem statements ==="
python3 "$SCRIPT_DIR/refine_problem_statements.py" "$DATA_DIR/MiroMindAI__miroflow"

echo "=== [sd-torchtune] Step 4: Refining problem statements ==="
python3 "$SCRIPT_DIR/refine_problem_statements.py" "$DATA_DIR/MiroMindAI__sd-torchtune"

echo "=== All repos processed. Output in $DATA_DIR ==="
